# Generated by Django 4.0.5 on 2022-11-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_about_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_or_tools',
            new_name='stack',
        ),
    ]
