# Generated by Django 4.0.5 on 2022-11-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github',
        ),
    ]
